### ISSUE TITLE
angular problem

### ISSUE THREAD

**Issue by assafSabag** [linnovate/icu#197]
### at first after run app
![default](https://cloud.githubusercontent.com/assets/12615452/13572859/3a4aaa3e-e485-11e5-8e33-d918357bcd53.PNG)
###  white screen and this problem:

05:05:09.080 Error: [$injector:modulerr] http://errors.angularjs.org/1.4.0-rc.0/$injector/modulerr?p0=mean&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.0-rc.0%2F%24injector%2Fmodulerr%3Fp0%3Dui.router%26p1%3D%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.4.0-rc.0%252F%2524injector%252Fnomod%253Fp0%253Dui.router%250AJ%252F%253C%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A6%253A421%250AZd%252F%253C%252F%253C%252F%253C%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A22%253A1%250Aa%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A22%253A141%250AZd%252F%253C%252F%253C%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A22%253A1%250Ah%252F%253C%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A36%253A286%250An%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A7%253A300%250Ah%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A36%253A134%250Ah%252F%253C%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A36%253A303%250An%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A7%253A300%250Ah%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A36%253A134%250A%2524a%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A39%253A416%250Auc%252Fd%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A18%253A381%250Auc%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fangular%252Fangular.min.js%253Frk4wmte29%253A19%253A179%250A%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fweb-bootstrap%252Findex.js%253Frk4wmte29%253A9%253A3%250An.Callbacks%252Fi%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fjquery%252Fdist%252Fjquery.min.js%253Frk4wmte29%253A2%253A27060%250An.Callbacks%252Fj.fireWith%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fjquery%252Fdist%252Fjquery.min.js%253Frk4wmte29%253A2%253A27828%250A.ready%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fjquery%252Fdist%252Fjquery.min.js%253Frk4wmte29%253A2%253A29619%250AJ%2540http%253A%252F%252Flocalhost%253A3000%252Fbower_components%252Fjquery%252Fdist%252Fjquery.min.js%253Frk4wmte29%253A2%253A29804%250A%0AJ%2F%3C%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3Frk4wmte29%3A6%3A421%0Ah%2F%3C%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3Frk4wmte29%3A37%3A56%0An%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3Frk4wmte29%3A7%3A300%0Ah%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3Frk4wmte29%3A36%3A134%0Ah%2F%3C%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3Frk4wmte29%3A36%3A303%0An%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3Frk4wmte29%3A7%3A300%0Ah%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3Frk4wmte29%3A36%3A134%0A%24a%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3Frk4wmte29%3A39%3A416%0Auc%2Fd%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3Frk4wmte29%3A18%3A381%0Auc%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.min.js%3Frk4wmte29%3A19%3A179%0A%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fweb-bootstrap%2Findex.js%3Frk4wmte29%3A9%3A3%0An.Callbacks%2Fi%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fjquery%2Fdist%2Fjquery.min.js%3Frk4wmte29%3A2%3A27060%0An.Callbacks%2Fj.fireWith%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fjquery%2Fdist%2Fjquery.min.js%3Frk4wmte29%3A2%3A27828%0A.ready%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fjquery%2Fdist%2Fjquery.min.js%3Frk4wmte29%3A2%3A29619%0AJ%40http%3A%2F%2Flocalhost%3A3000%2Fbower_components%2Fjquery%2Fdist%2Fjquery.min.js%3Frk4wmte29%3A2%3A29804%0A1 angular.min.js:6:420

### we change at /bower.json 

from "angular-ui-router": "#master",
to "angular-ui-router": "latest",

now we get:

![2](https://cloud.githubusercontent.com/assets/12615452/13572963/bfb6b0be-e485-11e5-91c8-66238ea90503.PNG)

### the app with this problem:

 http://errors.angularjs.org/1.4.0-rc.0/$injector/unpr?p0=%24modalProvider%20%3C-%20%24modal%20%3C-%20icuOpenModalDirective
J/<@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:6:421
$a/r.$injector<@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:39:288
d@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:37:266
$a/y.$injector<@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:39:360
d@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:37:266
e@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:38:1
t/</<@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:48:353
n@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:7:300
t/<@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:48:322
e@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:38:56
e/<@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:36:1
e@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:38:56
$a/y.$injector<@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:39:389
d@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:37:266
P@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:65:1
ya@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:55:194
Y@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:53:397
Y@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:54:55
Y@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:54:55
Y@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:54:55
Y@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:54:55
Y@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:54:55
Y@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:54:55
T@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:51:375
z/<.compile/<@http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.min.js?rr9snx3l3di:7:23677
aa@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:71:279
M@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:60:341
g@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:53:298
T/<@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:52:330
k@http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.min.js?rr9snx3l3di:7:23132
y/k.compile/<@http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.min.js?rr9snx3l3di:7:23409
aa@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:71:279
M@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:60:341
g@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:53:298
g@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:53:1
M@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:60:286
Gf/<@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:67:316
f/<@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:118:182
df/this.$get</m.prototype.$eval@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:132:217
df/this.$get</m.prototype.$digest@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:129:225
df/this.$get</m.prototype.$apply@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:132:497
l@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:85:193
O@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:89:252
Nf/</w.onload@http://localhost:3000/bower_components/angular/angular.min.js?rr9snx3l3di:90:289
"1 angular.min.js:106:325
e/<() angular.min.js:106
Ue/this.$get</<() angular.min.js:79
t/</<() angular.min.js:50
n() angular.min.js:7
t/<() angular.min.js:48
e() angular.min.js:38
e/<() angular.min.js:36
e() angular.min.js:38

### we think it happend because in new version the syntax is 'uibModal' instead of 'modal '

![image](https://cloud.githubusercontent.com/assets/12615452/13573042/46033840-e486-11e5-890b-0d54d363bd03.png)

**Comment by assafSabag** [comment]
@xanf @liorkesos  do you have any update about this issue?

**Comment by xanf** [comment]
@assafSabag Fix will be merged today
