### ISSUE TITLE
Don't die when there is no discussions/project

### ISSUE THREAD

**Issue by liorkesos** [linnovate/icu#198]
In the manual installation docs we need to bypass a certain situation like the paste below.
When building the page in angular it tries to get projects or discussions - we need to understand this state and not die but instead just give and alert (we will eventually get a design for  - "No projects/discussions - please create your first"

```
create fake project and discussion:
monogo
use icu-dev
db.projects.insert({ "_id" : ObjectId("56bb61181f1ee3eccc4aa8a2"), "created" : ISODate("2016-01-17T19:57:08.483Z"), "status" : "new", "watchers" : [ ], "creator" : ObjectId("56b864f1d5deaea71307a815"), "update" : ISODate("2016-01-17T19:57:08.582Z"), "title" : "", "color" : "b9e67d", "__v" : 1 })
db.discussions.insert({ "_id" : ObjectId("56bb64ec1f1ee3eccc4aa8a3"), "title" : "some discussion", "created" : ISODate("2015-11-25T13:11:24.358Z"), "updated" : ISODate("2015-11-25T13:11:24.358Z"), "creator" : ObjectId("56b864f1d5deaea71307a815"), "whatchers" : [ ], "members" : [ ], "status" : "new", "circles" : [  "authenticated" ], "__v" : 0 })
```

**Comment by assafSabag** [comment]
we still cant add project/tasks until we create fake project and discussion

before:

![screenshot from 2016-03-14 06 58 28](https://cloud.githubusercontent.com/assets/12615452/13747053/a269da44-e9b3-11e5-9224-ec97f0c66c6a.png)
:


after:

![screenshot from 2016-03-14 07 01 49](https://cloud.githubusercontent.com/assets/12615452/13747056/ae16a886-e9b3-11e5-8f78-a24708f905f6.png)
