### ISSUE TITLE
Not shows Projects from discussion && Discussions from Project

### ISSUE THREAD

**Issue by assafSabag** [linnovate/icu#210]
After creating new project from specific discussion, the project does not shown.
same thing happens if we are creating new discussion from specific project.

![screenshot from 2016-03-28 08 28 15](https://cloud.githubusercontent.com/assets/12615452/14081459/9e296ca8-f4bf-11e5-86c3-6176b327dfe4.png)
.

**Comment by assafSabag** [comment]
@liorkesos, @kaplanlior 
After @dvoras  fix this issue we close tag

**Comment by liorkesos** [comment]
ok - @kaplanlior will follow through with this one today
Lets get this tag out of the door
Lior

On Tue, Mar 29, 2016 at 12:41 AM, assafSabag <notifications@github.com>
wrote:

> @liorkesos <https://github.com/liorkesos>, @kaplanlior
> <https://github.com/kaplanlior>
> After @dvoras <https://github.com/dvoras> fix this issue we close tag
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/icu/issues/210#issuecomment-202591650>
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by kaplanlior** [comment]
Should be fixed by ff256e563bc97503a2450d6ee1f5494fb86a7fba
