### ISSUE TITLE
there is no name of project/discussions

### ISSUE THREAD

**Issue by assafSabag** [linnovate/icu#222]
@dvoras

**Comment by dvoras** [comment]
@assafSabag Did you pull from git the last fixes?

**Comment by kaplanlior** [comment]
Let's do discussions on slack instead of here.

**Comment by assafSabag** [comment]
Yes, it happened also in dev6
בתאריך 5 באפר 2016 08:42,‏ "Dvora Bundheim" <notifications@github.com> כתב:
